pull_request_rules:
  - name: Request reviews and label Steward's PRs
    conditions:
      - author=ssstlis-bot[bot]
    actions:
      request_reviews:
        users: [Ssstlis]
      label:
        add: [dependency-update]

  - name: Merge Steward's PRs
    conditions:
      - author=ssstlis-bot[bot]
      - or:
          - and:
              - "#files=1"
              - or:
                  - files=project/build.properties
                  - files=project/plugins.sbt
                  - files=build.sbt
          - body~=labels:.*semver-patch
          - "#approved-reviews-by>=1"
      - and:
          - check-success~=Test
          - label != do-not-merge
    actions:
      merge:
        method: squash
        commit_message_template: |
          {{ title }} (#{{ number }})

          {% for user in approved_reviews_by %}
          Approved-By: {{user}}
          {% endfor %}

merge_protections_settings:
  reporting_method: check-runs
